### ISSUE TITLE
Hey there!

### ISSUE THREAD

**Issue by MarianoKaz** [RikisuT/Youtube-Fluent-Theme#3]
I'm new to GitHub and I've been following your work with your Fluent Youtube design for quite some time now, I really REALLY love your work and I've been wondering about something that could use a bit of tweaking. You know about the Return Youtube Dislikes extension? It's pretty great and it works pretty well with your theme except for the like/dislike bar which somehow doesn't show up for Fluent Youtube. I just think it would complete the experience if you could figure out how to implement it there.

Here's Youtube with Fluent Theme:
![image](https://user-images.githubusercontent.com/112994471/188768405-0414a42d-5988-4466-9255-61c54db74886.png)

And here it is without the theme:
![image](https://user-images.githubusercontent.com/112994471/188768509-d9099a81-2e54-408a-804b-4d321c18472b.png)

**Comment by RikisuT** [comment]
Thank you for your feedback. 
I do have the Return YouTube Dislikes extension it seems to work in mine. When you say it does not work do you mean the bar below the like and dislike button that appears after you like or dislike a video?
If so then I haven't checked it, I'll look into it soon.

**Comment by MarianoKaz** [comment]
Yes, I was refering to the green/red bar below the likes and dislikes. And
weirdly enough it did use to work when I first tried the theme.

Mariano Goldheart

**Comment by RikisuT** [comment]
Sorry for being late. I had to attend classes. 
I have looked into it and now we have a problem. The extension was coded under the new UI menu not the old. The ratio bar dissapears when I set the display state of the new menu as none. I have no idea how to stick the two unrelated elements together.
It might be fixable using javascript but css has no possible solution, that I'm aware of, that would work dynamically.
Using css we cant make the bar change size and stick to the like/dislike buttons when changing the window size.
But you could set it to appear below the like/dislike buttons when the browser window is of a specific size.
I will continue looking for better solutions.

**Comment by MarianoKaz** [comment]
I see, but don't be pressured, I'll wait for as long as possible. Still
thanks for the news and good luck!

Mariano Goldheart

**Comment by RikisuT** [comment]
WOW I cant belive I hadn't thought of this solution...
This is an easy fix for this...
Just change, depending on your choice of theme, from this 
https://github.com/RikisuT/Youtube-Fluent-Theme/blob/4f07e54b8b110d348359434aeac3129ae5dd28e6/Themes/theme-with-caption-window-blur.css#L1295-L1297 or this
https://github.com/RikisuT/Youtube-Fluent-Theme/blob/e5f2e08712428b13c89f73f96c7af68e70cd4d64/Themes/theme.css#L1283-L1285 to this 
[return-youtube-dislikes-fix.css](https://github.com/RikisuT/Youtube-Fluent-Theme/blob/main/return-youtube-dislikes-fix.css)
The bar currently only appears when the page loads , when the page width is big enough to render the reccomended column.
It loads the best when it's fullscreen or close to that.
This adds an error of having extra area on the right when the browser width is small.
I will try configuring it so that it works fine when resizing the webpage.

**Comment by RikisuT** [comment]
Reduced the width error to around 700px before the bar clips away

**Comment by RikisuT** [comment]
Okkay it's kinda impossible to overlay the new bar over the old one after the alignment changes.
One could achive it by looking for window resizing like how its done for the sidebar, but I'm not well versed in that. 
I will set this issue as closed, but anyone reading this, if you have a possible solution, please do reopen the issue and comment.
