### ISSUE TITLE
Home Page Video Thumbnail Gallery Reärrangement (nav menu hidden)

### ISSUE THREAD

**Issue by easonwong-de** [RikisuT/Youtube-Fluent-Theme#4]
When the view port is wide enough and the navigation menu is automatically hidden, the video thumbnails could wrongly be placed in 4 columns. I think the 4 columns format is default, but 5 columns shall be correct for wide view port. (I’m using a 4K monitor)
<img width="2032" alt="Screen Shot 2022-10-16 at 01 49 53" src="https://user-images.githubusercontent.com/16183548/196011853-6378bbdb-83a9-49d2-95de-8fcb9383d77c.png">
Resizing the window slightly or revisiting the home page within the website (e.g. by clicking the YouTube icon on the left top) can correct it.
<img width="2032" alt="Screen Shot 2022-10-16 at 01 50 54" src="https://user-images.githubusercontent.com/16183548/196011845-959dd3d3-042f-4257-a43f-a437145ef489.png">
Some script should have been triggered when doing so. It would be nice if it could be done automatically.

**Comment by RikisuT** [comment]
This problem has existsted in this theme since the start.
I did not go for the reload route as it would change the reccomendation page, removing some videos that you may like. Also making it way slower.
The only possible way is to change the way the grid is made or refresh the grid. I'll look into it but it might take a long time as I have classes and I dont get time to keep updating this.
I'm sorry I could'nt help sooner.

**Comment by easonwong-de** [comment]
I’ve also tried some tricks, but none of them really helps. I’ll update you if I find a workaround. By the way, thank you for sharing the theme, it’s way better than the one on Stylish.

**Comment by easonwong-de** [comment]
Could be fixed with #5
